on:
  schedule:
  - cron: '0 1 * * *'
name: Build and Push Dockerfiles
jobs:
  dockerhub_publish_stable:
    name: DockerHub Build and Publish stable
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Build and Publish stable to DockerHub
      uses: westonsteimel/action-docker-publish@main
      with:
        registry: 'docker.io'
        password: ${{ secrets.DOCKER_PASSWORD }}
        username: ${{ secrets.DOCKER_USERNAME }}
        image_name: 'firefox'
        build_context: 'stable'
        dockerfile_path: 'stable/Dockerfile'
        tag_ref: false
        tag_latest: true
        tag_version: true
        tag_sha: false
        tag_timestamp: false
  dockerhub_publish_beta:
    name: DockerHub Build and Publish beta
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Build and Publish beta to DockerHub
      uses: westonsteimel/action-docker-publish@main
      with:
        registry: 'docker.io'
        password: ${{ secrets.DOCKER_PASSWORD }}
        username: ${{ secrets.DOCKER_USERNAME }}
        image_name: 'firefox'
        build_context: 'beta'
        dockerfile_path: 'beta/Dockerfile'
        tag_ref: false
        tag_latest: false
        tag_version: true
        tag_sha: false
        tag_timestamp: false
  dockerhub_publish_nightly:
    name: DockerHub Build and Publish nightly
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Build and Publish nightly to DockerHub
      uses: westonsteimel/action-docker-publish@main
      with:
        registry: 'docker.io'
        password: ${{ secrets.DOCKER_PASSWORD }}
        username: ${{ secrets.DOCKER_USERNAME }}
        image_name: 'firefox'
        build_context: 'nightly'
        dockerfile_path: 'nightly/Dockerfile'
        tag_ref: false
        tag_latest: false
        tag_version: true
        tag_sha: false
        tag_timestamp: true

